FROM node:24-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
# Gera browser para o Nginx e server para o app SSR
RUN npx ng build --configuration production --output-mode=server

FROM nginx:1.27-alpine AS runtime

RUN rm /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist/front-end-services/browser /usr/share/nginx/html
COPY nginx.ssr.conf /etc/nginx/conf.d/app.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
